workspace:
  base: /go
  path: src/github.com/skuid/dewey

pipeline:
  build:
    image: golang:1.9-alpine
    commands:
      - go build -v

  publish:
    image: quay.io/skuid/plugin-docker 
    registry: quay.io
    secrets: [docker_username, docker_password]
    repo: quay.io/skuid/dewey
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
